### PR TITLE
failing test (and updated example) corresponding to GitHub issue #4

### PR DESCRIPTION
**Pull request by laser**
This changeset contains the failing test corresponding to the [GitHub issue](https://github.com/deadmanssnitch/kafka/issues/4) that I submitted today. I tried to dig in and fix the bug myself, but thus far have failed.

### CODE REVIEW

**Comment by gaffneyc** [comment]
Thanks for reporting the issue and the failing test. I've pushed a commit that should fix it though I'm seeing there are other header functions that will need to be updated.

The [fix itself](https://github.com/deadmanssnitch/kafka/pull/5/commits/ddf0cf636b9e6ac41549924289b2ca2995ea6eb9) is that the pointer being passed to `rd_kafka_message_headers` was an input variable that itself needed to be read to know how to initialize the headers.

**Comment by laser** [comment]
Nice, thanks for the commit, and the fast reply.

**Comment by gaffneyc** [comment]
Thanks again! Sorry that I lost track of it after getting the fix in place.

**Comment by laser** [comment]
Nice! Thanks (cc @benortiz, @samsm)

**Pull request merged**
